"""add_reasoning_to_trades

Revision ID: 85552c1cd436
Revises: cc57c034c42c
Create Date: 2026-03-14 22:03:23.218619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85552c1cd436'
down_revision: Union[str, Sequence[str], None] = 'cc57c034c42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('reasoning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'reasoning')
    # ### end Alembic commands ###
